config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :orders
  devise_for :users
  get 'pages/index'

  resources :users

	root to: "pages#index"

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :status, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.fetch(:product, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content:"width=device-width, initial-scale=1.0"}
    %title Hackerstore
    %link{:href => "http://yui.yahooapis.com/pure/0.6.0/pure-min.css", :rel => "stylesheet"}/
    /[if lte IE 8]
    %link{:href => "http://yui.yahooapis.com/pure/0.6.0/grids-responsive-old-ie-min.css", :rel => "stylesheet"}
    / [if gt IE 8]>!
    %link{:href => "http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css", :rel => "stylesheet"}/
    / ![endif]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .custom-menu-wrapper
      .pure-menu.custom-menu.custom-menu-top
        %a.pure-menu-heading.custom-menu-brand{:href => "#"} Brand
        %a#toggle.custom-menu-toggle{:href => "#"}
          %s.bar
          %s.bar
      #tuckedMenu.pure-menu.pure-menu-horizontal.pure-menu-scrollable.custom-menu.custom-menu-bottom.custom-menu-tucked
        .custom-menu-screen
        %ul.pure-menu-list
          %li.pure-menu-item
            %a.pure-menu-link{:href => "#"} Home
          %li.pure-menu-item
            %a.pure-menu-link{:href => "#"} About
          %li.pure-menu-item
            %a.pure-menu-link{:href => "#"} Contact
          %li.pure-menu-item
            %a.pure-menu-link{:href => "#"} Blog
          %li.pure-menu-item
            %a.pure-menu-link{:href => "#"} GitHub
          %li.pure-menu-item
            %a.pure-menu-link{:href => "#"} Twitter
          %li.pure-menu-item
            %a.pure-menu-link{:href => "#"} Apple
          %li.pure-menu-item
            %a.pure-menu-link{:href => "#"} Google
          %li.pure-menu-item
            %a.pure-menu-link{:href => "#"} Wang
          %li.pure-menu-item
            %a.pure-menu-link{:href => "#"} Yahoo
          %li.pure-menu-item
            %a.pure-menu-link{:href => "#"} W3C
    :javascript
      (function (window, document) {
      document.getElementById('toggle').addEventListener('click', function (e) {
          document.getElementById('tuckedMenu').classList.toggle('custom-menu-tucked');
          document.getElementById('toggle').classList.toggle('x');
      });
      })(this, this.document);
    .main
      = yield

app/views/orders/_form.html.haml
= form_for(@order) do |f|
  - if @order.errors.any?
    #error_explanation
      %h2
        = pluralize(@order.errors.count, "error")
        prohibited this order from being saved:
      %ul
        - @order.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :status
    %br/
    = f.number_field :status
  .field
    = f.label :user_id
    %br/
    = f.text_field :user_id
  .actions
    = f.submit

app/views/orders/edit.html.haml
%h1 Editing Order
= render 'form'
= link_to 'Show', @order
|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%p#notice= notice
%h1 Listing Orders
%table
  %thead
    %tr
      %th Name
      %th Status
      %th User
      %th{:colspan => "3"}
  %tbody
    - @orders.each do |order|
      %tr
        %td= order.name
        %td= order.status
        %td= order.user
        %td= link_to 'Show', order
        %td= link_to 'Edit', edit_order_path(order)
        %td= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Order', new_order_path

app/views/orders/new.html.haml
%h1 New Order
= render 'form'
= link_to 'Back', orders_path

app/views/orders/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @order.name
%p
  %strong Status:
  = @order.status
%p
  %strong User:
  = @order.user
= link_to 'Edit', edit_order_path(@order)
|
= link_to 'Back', orders_path

app/views/pages/index.html.haml
%h1 Pages#index
%p Find me in app/views/pages/index.html.erb

app/views/products/_form.html.haml
= form_for(@product) do |f|
  - if @product.errors.any?
    #error_explanation
      %h2
        = pluralize(@product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - @product.errors.full_messages.each do |message|
          %li= message
  .actions
    = f.submit

app/views/products/edit.html.haml
%h1 Editing Product
= render 'form'
= link_to 'Show', @product
|
= link_to 'Back', products_path

app/views/products/index.html.haml
%p#notice= notice
%h1 Listing Products
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @products.each do |product|
      %tr
        %td= link_to 'Show', product
        %td= link_to 'Edit', edit_product_path(product)
        %td= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New Product
= render 'form'
= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_product_path(@product)
|
= link_to 'Back', products_path

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/users/edit.html.haml
%h1 Editing User
= render 'form'
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.haml
%p#notice= notice
%h1 Listing Users
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New User
= render 'form'
= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @user.name
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path